version: '3'
services:
  positions_app:
    build:
      context: .
      dockerfile: ./apps/positions/Dockerfile
      target: development
    command: pnpm run start:dev positions
    env_file:
      - ./apps/positions/.env.development
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    networks:
      - positions_db
      - auth_db

  auth_app:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env.development
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    networks:
      - positions_db
      - auth_db

  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - positions_db
      - auth_db

networks:
  positions_db:
    name: positions_db
  auth_db:
    name: auth_db
